### PR TITLE
h

### PR DESCRIPTION
**Pull request by ajskateboarder**

### CODE REVIEW

**Comment by familycomicsstudios** [comment]
Please no i need it to be cringe

**Comment by themysticsavages** [comment]
> Please no i need it to be cringe

Why exactly?

**Comment by familycomicsstudios** [comment]
> > Please no i need it to be cringe
> 
> Why exactly?

It's funny

**Comment by familycomicsstudios** [comment]
Keep the cringe

**Comment by themysticsavages** [comment]
Cringe !== funny

**Pull request closed without merging**
